---
- hosts: all
  become: yes
  tasks:
    - name: install Java8 on Ubuntu
      apt:
         name: default-jdk
         state: present
      when: ansible_os_family == "Debian"
    - name: install Java8 on Redhat
      yum:
        name: java-1.8.0-openjdk-devel
        state: present
      when: ansible_os_family == "RedHat"
    - name: Install tomcat on Ubuntu
      apt: 
        - name: tomcat7
          state: present
        - name: apache2
          state: present
      notify:
      - restart apache2       
      when: ansible_os_family == "Debian"
    - name: install tomcat on Rehat
      yum: 
         package: "{{ item }}"
         state: present
      with_items: "{{ httpd, tomcat }}"
      notify:
      - restart httpd
      when: ansible_os_family == "Redhat"
    - name: download and copy openmrs war file to tomcat webapps
      get_url: 
         url: "{{ openmrsurl }}"
         dest: "{{ tomcat }}"
      notify:
      - restart tomcat
      when: ansible_os_family == "RedHat"
      get_url:
          url:  "{{ openmrsurl }}"
          dest: "{{ tomcat7 }}"
      notify:
      - restart tomcat
      when: ansible_os_family == "Debian"
      handlers:
       - name: restart httpd
         service:
             name: httpd
             state: restarted
       - name: restart apache2
         service:
             name: apache2
             state: restarted
       - name: restart tomcat
         service: 
             name: tomcat
             state: restarted

          
    
      

         





      
 


      
    
      
