---
- hosts: all
  become: yes
  tasks:
  - name: Install httpd on redhat
    when: ansible_os_family == "RedHat"
    yum:
       name: httpd
       state: absent
  - service:
       name: httpd
       state: stopped
  - name: Install Apache2 on ubuntu
    when: ansible_os_family == "Debian"
    apt:
      name: apache2
      state: absent
      update_cache: yes
  - service:
       name: apache2
       state: stopped

