---
# Copy Module Example
- hosts: redhat
  become: yes
  tasks:
  - name: Copy from the files directory test file
    copy:
      src: files/test2.txt
      dest: /tmp/test2.txt
      mode: 0644
      owner: ansible
      group: ansible
      backup: yes
