---
- hosts: all
  tasks:
  - name: execute basic linux command
    command: hostname -f
    register: cmd_content
  - name: print the content
    debug:
      msg: " {{ cmd_content.stdout }} "
    when: cmd_content.stderr == ""
  - name: print command error if present
    debug:
      msg: " {{ cmd_content.stderr}} "
    when: cmd_content.stderr != ""
  - name: printing diff between register and debug
    debug:
      msg: "system {{ inventory_hostname }} has uuid {{ ansible_product_uuid }}"
