---
- hosts: all
  become: yes
  tasks:
  - name: Install apache on redhat
    yum: 
      name: httpd
      state: "{{ status }}"
      when: ansible_os_family == "RedHat"
      notify: "start httpd"
  - name: Install apache on ubuntu
    apt:
      name: apache2
      state: "{{ status }}"
      when: ansible_os_family == "Debian"
      notify: "start apache2"
  - name: defining Handlers
    handlers:
      - listen: "start httpd"
        service:
           name: httpd
           state: started
      - listen: "start apache2"
        service: 
           name: apache2
           state: started
