---
# The Pasue Module
- hosts: redhat
  sudo: yes
  gather_facts: no
  tasks:
  - name: Install httpd
    yum:
      name: httpd
      state: present
  - name: Pasuing playbook
    pause:
      #prompt: "Make sure the installation is complete..."
      seconds: 10
  - name: Verify Lynx Installation
    yum:
      name: curl
      state: present
      

