---
- hosts: all
  become: yes
  tasks: 
  - name: basic template with dynamic content
    template: 
       src: basic.j2
       dest: /home/ansible/basic
    template:
       src: tomcat7.j2
       dest: /etc/default/tomcat7    

