---
- hosts: all
  become: yes
  tasks:
  - name: Install httpd on redhat
    yum: 
       name: httpd
       state: present
       when: ansible_os_family == "RedHat"
  - service: 
       name: httpd
       state: started
  - name: Install Apache2 on ubuntu
    apt: 
      name: apache2
      state: present
      update_cache: yes
      when: ansible_os_family == "Debian"
  - service:
       name: apache2
       state: started
