---
- hosts: all
  become: yes
  tasks:
  - name: Install Apache2 on ubuntu
    when: ansible_os_family == "Debian"
    apt: 
      name: apache2
      state: present
      update_cache: yes
  - name: Install httpd on redhat
    when: ansible_os_family == "RedHat"
      - yum: 
          name: httpd
          state: present
      - service:
          name: httpd
          state: started
