---
- hosts: ubuntu
  become: yes
  tasks:
   - name: Install tomcat on ubuntu
     apt:
      name: tomcat7
      state: present
      update_cache: yes
   - service:
      name: tomcat7
      state: started
