---
# The wait for module
- hosts: ubuntu
  become: yes
  gather_facts: no
  tasks:
  - name: Install Apache tomcat
    yum:
      name: tomcat7
      state: present
  - name: Waiting for the port to listen
    wait_for:
      port: 8080
      state: started
  - name: Verify Curl Installation
    yum:
      name: curl
      state: present