---
# tasks file for common
- name: install packages on Ubuntu
  command: apt-get update
  when: ansible_os_family == "Debian"
- name: install packages on Redhat
  command: yum update
  when: ansible_os_family == "RedHat"