---
- hosts: all
  become: yes
  tasks:
  - name: Uninstall httpd on redhat machines
    yum:
      name: httpd
      state: absent
    when: ansible_os_family == "RedHat"
  - name: Uninstall apache2 on ubuntu machines
    apt:
      name: apache2
      state: absent
    when: ansible_os_family == "Debian" 