---
- hosts: ubuntu
  become: yes
  tasks:
  - name: install apache2 and tomcat on ubuntu
    apt:
      name: "{{ item }}"
      state: present
      enabled: yes
    with_items: 
      - apache2
      - tomcat7