---
- hosts: all
  become: yes
  gather_facts: no
  tasks:
  - name: start ec2 instances
    ec2:
      state: present
      ec2_ami: 
  - name: create a user
    user:
       name: tomcat
       state: present
  - name: Create a group 
    group:
       name: tomcat
       state: present
       groupdel: xxx
  - name: remove log folder
    command: "rm -rf /var/logs/"
  - name: copy the config file
    copy:
      src: /var/log/
      dest: /tmp/caretools/
  - name: download tomcat war
    get_url:
       url: http://google.com/path/file.conf
       dest: /tmp/extras/
       



    
    
       


      